### ISSUE TITLE
Webpack config error

### ISSUE THREAD

**Issue by chriscurnow** [tianyangj/angular-cli#1]
Hi,

This looks like a great project. Thanks for putting it together.

I just cloned it and ran npm install.

However, when I tried ng serve, I got the following output:

`WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.`
`- configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     }`
 `- configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).`
 `- configuration.node.global should be a boolean.`
 `- configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }`
 `- configuration.resolve.extensions[0] should not be empty.
    at webpack (/Projects/web-apps/angular-cli/node_modules/webpack/lib/webpack.js:16:9)
    at Class.exports.default.Task.extend.run (/Projects/web-apps/angular-cli/node_modules/angular-cli/tasks/serve-webpack.js:23:27)
    at /Projects/web-apps/angular-cli/node_modules/angular-cli/commands/serve.js:84:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
`

Any ideas about what I might be doing wrong. 

I'll keep investigating and see if I can't find out what is happening but I thought I would report it here in case someone else has already come across it.

**Comment by chriscurnow** [comment]
OK, the problem was that I had forgotten to update my global angular-cli.

All good now.
